### ISSUE TITLE
Allow special account to archive members

### ISSUE THREAD

**Issue by kistora** [K-Fet/K-App#230]
Create:
- A new permission called `member:archive`
- A new endpoint `POST /members/archivate` with `codeGuard` 
- A new botton in front.

Update:
- Member list component to navigate in different years
- `GET /members` to `GET /members/xxxx` where xxxx is the year

**Comment by Embraser01** [comment]
Who should do this task? The webmaster, the president,the member manager special account, another special account?

**Comment by Embraser01** [comment]
Also, we should think about how o retreive a member from another year...

It would implied a few more things:

I think it would be nice (for stats) to save every for a member, each year he has been a member. It means that we have to create a model which have the year of membership and maybe the time where he register.

At creation we could do an autocomplete with search to find the member first or create a new one.

If he already exists, just display a button `Register for the year 20XX-20XX`.
Otherwise, create a new member and register him for the current year.

## Structure

We could have a model for a `Registration`:
- `member`
- `year`: string `20XX-20XX` (or two field idk)
- `time`: Time of registration


We could remove the field `active` of the member after this (to know if it's active, just lookup member of this current year).

What do you think about all this @kistora?

**Comment by kistora** [comment]
Ok, let's do that !
What do you propose about the different endpoints ?
