### ISSUE TITLE
Increase request rate limit in prod, remove the restriction in dev/test

### ISSUE THREAD

**Issue by kistora** [K-Fet/K-App#310]
**Describe the bug**

In production, we schould increase rate limit in order to remove anoying `Too many request error` (code 429).
![image](https://user-images.githubusercontent.com/29222996/47174112-c20c6e00-d2dd-11e8-8667-3caeedca964e.png)

In dev mode, we schould remove this restriction.

**Screenshots**
![image](https://user-images.githubusercontent.com/29222996/47174236-0ef04480-d2de-11e8-820f-8be1c38e890f.png)

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Comment by Embraser01** [comment]
In which cases does this happens? It is a restriction that is only on auth routes...

**Comment by kistora** [comment]
Password (re)definition. It happens to a barman (in prod env) and to me when i tried to reproduce the bug.
My point is: for now, a normal trafic is considered as spucious traffic...

**Comment by kistora** [comment]
`[2018-10-18T13:55:32] warn: [RATE LIMIT REACHED]: For request /reset-password by ::ffff:127.0.0.1 
`

**Comment by Embraser01** [comment]
As I can see, it happend for two different ips (the rate limit is set per IPs).
The first one was probably done on the Wi-Fi K-Fêt and the other done on 4G. Anyway, this must have happend after 5 fails...

I can increase this number (I don't really see the point to disabled it in dev) because in the case multiple devices do request from the same network (e.g. WiFi K-Fêt), it will count as one device.

**Comment by kistora** [comment]
As you want :)

**Comment by Embraser01** [comment]
I will look into it tomorrow morning :smile:
Anyway, I will set the reject time at 15min instead of 20min and increase number of attemps to 10 failed requests.
